using System.Collections.Generic;
using UnityEngine;

public class TT_QuestionManager : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private List<string> MostLikely = new List<string>()
    {
        "Who's most likely to work overtime without getting paid",
        "Who's most likely to quit their job on a whim?",
        "Who's most likely to become a CEO?",
        "Who's most likely to fall asleep during a meeting?",
        "Who's most likely to be late for work every day?",
        "Who's most likely to miss your wedding?",
        "Who's most likely to ghost someone after a first date?",
        "Who's most likely to get married in Vegas?",
        "Who's most likely to forget your birthday?",
        "Who's most likely to cry at a rom-com?",
        "Who's most likely to eat their birthday cake alone?",
        "Who's most likely to steal food off someone else's plate?",
        "Who's most likely to order takeout every day?",
        "Who's most likely to burn their dinner?",
        "Who's most likely to finish a whole pizza by themselves?",
        "Who's most likely to lose their phone?",
        "Who's most likely to start a conversation with a stranger?",
        "Who's most likely to laugh at a bad joke?",
        "Who's most likely to become famous?",
        "Who's most likely to forget their wallet at home?",
        "Who's most likely to backpack across the world?",
        "Who's most likely to get lost in their own city?",
        "Who's most likely to plan a spontaneous road trip?",
        "Who's most likely to cancel travel plans last minute?",
        "Who's most likely to move to another country?",
        "Who's most likely to sing karaoke in public?",
        "Who's most likely to dye their hair a crazy color?",
        "Who's most likely to binge-watch a series in one night?",
        "Who's most likely to accidentally send a text to the wrong person?",
        "Who's most likely to win a lottery and lose the ticket?",
        "Who's most likely to retire early?",
        "Who's most likely to adopt ten pets?",
        "Who's most likely to start their own business?",
        "Who's most likely to move off the grid?",
        "Who's most likely to run for public office?",
        "Who's most likely to trip over their own feet?",
        "Who's most likely to adopt an unusual hobby?",
        "Who's most likely to get stuck in an elevator?",
        "Who's most likely to spend hours on a pointless internet rabbit hole?",
        "Who's most likely to prank their friends?",
        "Who's most likely to start their own company?",
        "Who's most likely to get fired on their first day?",
        "Who's most likely to become a billionaire?",
        "Who's most likely to win an employee of the month award?",
        "Who's most likely to become a motivational speaker?",
        "Who's most likely to forget about an important meeting?",
        "Who's most likely to stay at the same job forever?",
        "Who's most likely to change careers five times?",
        "Who's most likely to invent something that changes the world?",
        "Who's most likely to fake being sick to avoid work?",
        "Who's most likely to have a whirlwind romance?",
        "Who's most likely to fall in love with a celebrity?",
        "Who's most likely to elope?",
        "Who's most likely to get married first?",
        "Who's most likely to get engaged and call it off?",
        "Who's most likely to stay single forever?",
        "Who's most likely to forget their partner's anniversary?",
        "Who's most likely to write a love poem?",
        "Who's most likely to propose in a very public way?",
        "Who's most likely to date their best friend?",
        "Who's most likely to organize a surprise party?",
        "Who's most likely to bail on plans last minute?",
        "Who's most likely to skip leg day?",
        "Who's most likely to win an argument?",
        "Who's most likely to start a group chat?",
        "Who's most likely to keep a secret forever?",
        "Who's most likely to borrow something and forget to return it?",
        "Who's most likely to be the peacemaker in a fight?",
        "Who's most likely to always remember everyone's birthday?",
        "Who's most likely to bring snacks to a gathering?",
        "Who's most likely to invite a random stranger to hang out?",
        "Who's most likely to visit all seven continents?",
        "Who's most likely to forget their passport at the airport?",
        "Who's most likely to travel to space?",
        "Who's most likely to plan a trip but never go?",
        "Who's most likely to spend all their money on travel?",
        "Who's most likely to go on an adventure?",
        "Who's most likely to have the unhealthiest diet?",
        "Who's most likely to live out of a van in a bush?",
        "Who's most likely to move to a tropical island?",
        "Who's most likely to befriend a local on a trip?",
        "Who's most likely to take 1,000 photos on a vacation?",
        "Who's most likely to talk to animals as if they understand?",
        "Who's most likely to buy something ridiculous online?",
        "Who's most likely to spend a day doing absolutely nothing?",
        "Who's most likely to fall asleep during a movie?",
        "Who's most likely to eat a whole cake by themselves?",
        "Who's most likely to laugh at their own jokes?",
        "Who's most likely to adopt a strange pet?",
        "Who's most likely to dress up for no reason?",
        "Who's most likely to forget where they parked their car?",
        "Who's most likely to become a memer?",
        "Who's most likely to become president?",
        "Who's most likely to retire before 40?",
        "Who's most likely to write a bestselling book?",
        "Who's most likely to live to be 100 years old?",
        "Who's most likely to own a private jet?",
        "Who's most likely to become a teacher?",
        "Who's most likely to live off the grid?",
        "Who's most likely to adopt someone's kid?",
        "Who's most likely to make a joke at the worst time?",
        "Who's most likely to overthink a small situation?",
        "Who's most likely to always be late?",
        "Who's most likely to never answer their phone?",
        "Who's most likely to befriend a celebrity?",
        "Who's most likely to accidentally start a fire?",
        "Who's most likely to trip and fall in public?",
        "Who's most likely to sing in the shower loudly?",
        "Who's most likely to lose their keys every day?",
        "Who's most likely to lock themselves out of their house?",
        "Who's most likely to talk during a movie?",
        "Who's most likely to prank someone?",
        "Who's most likely to forget what they were saying mid-sentence?",
        "Who's most likely to break a world record?",
        "Who's most likely to lose a game and blame the rules?",
        "Who's most likely to post a selfie during a natural disaster?",
        "Who's most likely to walk into the wrong bathroom?",
        "Who's most likely to forget someone's name right after meeting them?",
        "Who's most likely to text their ex while drunk?",
        "Who's most likely to get caught talking to themselves?",
        "Who's most likely to accidentally like an old Instagram post while stalking someone?",
        "Who's most likely to spill their drink on someone at a party?",
        "Who's most likely to show up to an event in the wrong outfit?",
        "Who's most likely to forget they were supposed to bring a gift to a party?",
        "Who's most likely to trip over their own shoelaces?",
        "Who's most likely to join a cult?",
        "Who's most likely to talk to a ghost if they see one?",
        "Who's most likely to survive a zombie apocalypse?",
        "Who's most likely to buy a weird gadget they'll never use?",
        "Who's most likely to name their pet something ridiculous?",
        "Who's most likely to randomly burst into song in public?",
        "Who's most likely to argue that time travel is real?",
        "Who's most likely to have a collection of something odd?",
        "Who's most likely to eat dessert before dinner?",
        "Who's most likely to order the same meal every time?",
        "Who's most likely to experiment with a crazy food combination?",
        "Who's most likely to burn water while cooking?",
        "Who's most likely to hoard snacks in their room?",
        "Who's most likely to eat an entire tub of ice cream in one sitting?",
        "Who's most likely to win a hotdog-eating contest?",
        "Who's most likely to forget they ordered food delivery?",
        "Who's most likely to eat something they dropped on the floor?",
        "Who's most likely to try a fad diet just for fun?",
        "Who's most likely to spend all day in pajamas?",
        "Who's most likely to fall asleep on the couch during a party?",
        "Who's most likely to call someone to pick up something they forgot 5 feet away?",
        "Who's most likely to leave dishes in the sink for a week?",
        "Who's most likely to procrastinate until the very last minute?",
        "Who's most likely to pretend to be busy to avoid plans?",
        "Who's most likely to spend hours scrolling on their phone?",
        "Who's most likely to cancel plans just to stay home?",
        "Who's most likely to take a nap in the middle of the day for no reason?",
        "Who's most likely to wear the same outfit two days in a row?",
        "Who's most likely to skydive?",
        "Who's most likely to swim with sharks?",
        "Who's most likely to ride the scariest rollercoaster?",
        "Who's most likely to try bungee jumping?",
        "Who's most likely to climb Mount Everest?",
        "Who's most likely to book a spontaneous trip to another country?",
        "Who's most likely to survive in the wilderness for a week?",
        "Who's most likely to jump off a cliff into water?",
        "Who's most likely to sign up for an extreme obstacle course?",
        "Who's most likely to explore a haunted house alone?",
        "Who's most likely to go viral on TikTok?",
        "Who's most likely to forget their password every time?",
        "Who's most likely to watch the entire Movie Series in one weekend?",
        "Who's most likely to build a robot?",
        "Who's most likely to buy the latest gadget the moment it's released?",
        "Who's most likely to watch YouTube videos all day?",
        "Who's most likely to accidentally send an embarrassing email at work?",
        "Who's most likely to write fan fiction about their favorite show?",
        "Who's most likely to forget there's a test?",
        "Who's most likely to fall asleep in class?",
        "Who's most likely to finish an assignment the night before?",
        "Who's most likely to write a fake doctor's note to skip school?",
        "Who's most likely to organize a study group and not show up?",
        "Who's most likely to get caught cheating?",
        "Who's most likely to become the teacher's favorite?",
        "Who's most likely to lose their school ID?",
        "Who's most likely to be rocking a face full of makeup, even for a swim?"

        // I'll stop here for the mean time!



    };

    private List<string> NameThreeThings = new List<string>()
    {
        "Name three things you would bring to a deserted island.",
        "Name three foods you could eat for the rest of your life.",
        "Name three animals you'd want as pets if money wasn't an issue.",
        "Name three animals starting with letter 'G'",
        "Name three birds",
        "Name three animals commonly found in a desert",
        "Name three things you'd never do for a million dollars.",
        "Name three things you'd do with a million dollars.",
        "Name three worst gifts you ever received",
        "Name three words starting with letter 'K'",
        "Name three things with a knob.",
        "Name three types of nut.",
        "Name three continents",
        "Name three things you can chew on",
        "Name three characters from the Bible",
        "Name three upper body parts",
        "Name three people that are smarter than you",
        "Name three European countries",
        "Name three jobs that pay well",
        "Name three capital cities",
        "Name three shoe brands",
        "Name three movies with talking animals",
        "Name three football teams",
        "Name three cleaning tools",
        "Name three things you can find in a school",
        "Name three things you can find in a market",
        "Name three things you can find in an airplane",
        "Name three things you can find in a river",
        "Name three things you can find in a serial killer's house",
        "Name three words that rhyme with 'how'",
        "Name three means of transport",
        "Name three soccer stadiums",
        "Name three boy names",
        "Name three girl names",
        "Name three African dishes",
        "Name three European dishes",
        "Name three things made out of glass",
        "Name three French words",
        "Name three places where people keep their money",
        "Name three planets",
        "Name three Spanish words",
        "Name three ways to become a millionaire",
        "Name three animals with two legs",
        "Name three things you drive",
        "Name three things you can't resist",
        "Name three Christmas songs",
        "Name three types of fish",
        "Name three things made out of rubber",
        "Name three ball sports",
        "Name three colours that are not in the rainbow",
        "Name three animals that lay eggs",
        "Name three free things",
        "Name three things made out of wood",
        "Name three individual sports",
        "Name three things that are hot",
        "Name three things that are cold",
        "Name three Asian countries",
        "Name three African countries",
        "Name three reptiles",
        "Name three tech jobs",
        "Name three mammals",
        "Name three things you can find around here",
        "Name three things that are always in your fridge.",
        "Name three songs you would play on repeat forever.",
        "Name three movies you could watch over and over again.",
        "Name three yellow foods",
        "Name three words Disney songs",
        "Name three words disney songs",
        "Name three professions",
        "Name three words starting with letter 'K'",
        "Name three words starting with letter 'C'",
        "Name three things you can't live without.",
        "Name three people you'd invite to a dinner party.",
        "Name three things you wish you knew how to do.",
        "Name three things you'd buy if you won the lottery.",
        "Name three excuses you would use to avoid going out.",
        "Name three things that always make you laugh.",
        "Name three things you'd do if you woke up with superpowers.",
        "Name three fruits starting with letter 'P'",
        "Name three things you'd never want to be famous for.",
        "Name three things that are guaranteed to embarrass you.",
        "Name three things you'd do if you were invisible for a day.",
        "Name three people you would call in a crisis.",
        "Name three things that should never be mixed together.",
        "Name three things you're afraid of, even though you know they're not dangerous.",
        "Name three things you're not afraid of, even though you know they're dangerous.",
        "Name three places you'd love to travel to.",
        "Name three countries you think are overrated.",
        "Name three things you would take on a road trip.",
        "Name three things you would do if you were a tourist in your own city.",
        "Name three places you'd hide if a zombie apocalypse happened.",
        "Name three animals starting with letter 'L'",
        "Name three countries you would never visit.",
        "Name three ways to travel the world without flying.",
        "Name three people you'd take with you on a backpacking adventure.",
        "Name three things that could ruin a first date.",
        "Name three things you'd do if you turned into the opposite gender for a day.",
        "Name three things you've done that you would never do again.",
        "Name three words starting with letter 'Q'",
        "Name three embarrassing moments you could laugh about now.",
        "Name three things that would make you scream.",
        "Name three things you've accidentally broken.",
        "Name three things you can never remember where you put.",
        "Name three bad habits you need to break.",
        "Name three things you do when no one's watching.",
        "Name three habits you have that annoy others.",
        "Name three things you're really good at, but no one knows about.",
        "Name three things you do when you're bored.",
        "Name three ways to make a boring day fun.",
        "Name three things that make life more interesting.",
        "Name three things you hope to do before you die.",
        "Name three things you've done that made you feel brave.",
        "Name three words starting with letter 'I'",
        "Name three apps you use every day.",
        "Name three things you can't live without in the digital age.",
        "Name three fictional characters you'd invite to dinner.",
        "Name three social media platforms you use the most.",
        "Name three things you'd do if you became the President for a day.",
        "Name three superpowers you wish you had.",
        "Name three animals you could use as your personal bodyguards.",
        "Name three things you'd do if you woke up with the ability to speak every language.",
        "Name three scenarios you'd create if you had the power to control time.",
        "Name three things you'd build if you were given unlimited resources.",
        "Name three things you'd change about the world if you had the power to.",
        "Name three places you'd visit if there were no rules or restrictions.",
        "Name three words starting with letter 'U'",
        "Name three things you'd do if you were the only human left on Earth.",
        "Name three things you would bring to a fight with a wild animal.",
        "Name three ways to show someone you love them without saying it.",
        "Name three things that would make you fall in love with someone instantly.",
        "Name three things you'd give to your best friend as a surprise gift.",
        "Name three things you'd want to build if you were an inventor.",
        "Name three objects you'd want in your dream home.",
        "Name three movies you'd make if you were a director.",
        "Name three activities you'd do if you were locked in a room for 24 hours.",
        "Name three things you would do on a day without any rules.",
        "Name three places you'd visit if you could teleport anywhere.",
        "Name three words starting with letter 'O'",
        "Name three things you'd do if you suddenly became a billionaire.",
        "Name three things that should be illegal.",
        "Name three moments in your life you wish you could relive.",
        "Name three things you'd use a robot for if you could.",
        "Name three things you would do if you could swap lives with someone for a week.",
        "Name three historical figures (dead or alive) you would invite to a dinner party.",
        "Name three ways the world would change if everyone could read minds.",
        "Name three things that would happen if all animals could talk.",
        "Name three things you would do if you could breathe underwater for a day.",
        "Name three fictional characters you would want as a roommate.",
        "Name three dishes you could eat for the rest of your life.",
        "Name three unusual food combinations that you actually love.",
        "Name three foods you'd never eat under any circumstances.",
        "Name three feminine names starting with letter 'E'",
        "Name three male names starting with letter 'G'",
        "Name three things you do every morning without fail.",
        "Name three modes of transportation you'd love to try.",
        "Name three things that could instantly make your day better.",
        "Name three things you would do if you could talk to animals.",
        "Name three things you think would happen if gravity was turned off for a day.",
        "Name three people who inspire you to be better.",
        "Name three things you want to achieve by the end of this year.",
        "Name three animals you think are underrated.",
        "Name three facts about space that you find mind-blowing.",
        "Name three things you think could exist on other planets.",
        "Name three male names starting with letter 'S'",
        "Name three things you would take with you if you had to survive in the wilderness for a week.",
        "Name three ways you would spend your last day on Earth.",
        "Name three people you would want to be stuck in an elevator with.",
        "Name three cartoons you loved growing up.",
        "Name three childhood friends you still keep in touch with.",
        "Name three things that remind you of your childhood.",
        "Name three memories you will always cherish from your childhood.",
        "Name three things that have stayed with you since your childhood.",
        "Name three favorite snacks you ate as a kid.",
        "Name three clothing items you can't live without.",
        "Name three colors you think always look good together.",
        "Name three things that are always in your bag or pocket when you leave the house.",
        "Name three things you think are more important than money.",
        "Name three questions you wish you had the answers to.",
        "Name three female names starting with letter 'B'",
        "Name three people you'd love to meet in person.",
        "Name three things that should never be done in public.",
        "Name three ways to waste money",
        "Name three words starting with letter 'K'",

    };

    private List<string> Sexy = new List<string>()
    {
        "What's the most romantic gesture you've ever experienced?",
        "What's your idea of the perfect date night?",
        "If you could kiss anyone right now, who would it be?",
        "What's the most attractive quality in a partner?",
        "What's your favorite way to flirt?",
        "What's the best compliment you’ve ever received?",
        "What's your ultimate turn-on?",
        "What's something that instantly makes someone more attractive to you?",
        "Describe your perfect cuddle session.",
        "What's your favorite type of intimate gesture?",
        "What's the first thing you notice about someone you're attracted to?",
        "How do you like to be touched?",
        "What's your favorite part of foreplay?",
        "What would be your idea of a perfect night in?",
        "What's the most seductive outfit you can imagine?",
        "What's the most intimate compliment someone could give you?",
        "What's the one thing that turns you on more than anything?",
        "What's the most daring thing you've ever done in the name of love?",
        "How do you like to be kissed?",
        "What type of touch sends shivers down your spine?",
        "What's your favorite way to be kissed?",
        "What's your idea of the perfect date for two?",
        "What's your favorite way to tease someone?",
        "What's the most sensual experience you've ever had?",
        "Do you like it when someone takes control, or do you prefer being in control?",
        "What kind of music makes you feel the most seductive?",
        "Do you believe in love at first sight, or should I walk by again?",
        "What's your favorite body part to kiss?",
        "How do you feel about slow, lingering touches?",
        "What's the most romantic thing someone could do for you?",
        "Do you like to be surprised with spontaneous affection?",
        "What's something you've always wanted to try but never have?",
        "What's your favorite way to flirt?",
        "What's the most playful thing you've ever done in the name of romance?",
        "What do you find most attractive in someone's voice?",
        "What's the best way to show you affection?",
        "How do you feel about a partner making you feel desired?",
        "What makes you feel the most attractive?",
        "How would you describe your perfect kiss?",
        "What's your favorite way to wake up next to someone?",
        "What's your idea of a romantic getaway?",
        "What's the best thing someone could do to turn you on?",
        "What's the most flirtatious thing you've done recently?",
        "What's the sexiest thing someone could say to you?",
        "Do you like to be whispered to in the dark?",
        "What's your favorite way to make someone smile seductively?",
        "What's the best compliment you can give to someone you desire?",
        "What's something that makes you feel irresistible?",
        "Do you prefer a quiet, intimate night or a wild, spontaneous evening?",
        "What's your favorite part of someone's body to kiss or touch?",
        "How do you feel about PDA (public displays of affection)?",
        "What's your most sensual memory?",
        "Do you enjoy giving or receiving massages?",
        "What's the most seductive gesture someone can do?",
        "What kind of clothes make you feel confident and sexy?",
        "What's the most intimate place you've ever kissed someone?",
        "What makes someone's touch feel irresistible to you?",
        "What's something that always gets your attention in a person?",
        "What's your favorite type of flirtatious smile?",
        "Do you believe in chemistry between two people? How do you feel it?",
        "What's your favorite love language?",
        "What's the most intimate thing someone could say to you?",
        "What's your idea of the ultimate romantic night?",
        "What do you like about the way someone looks at you?",
        "What's the best way to draw you in and make you want someone?",
        "What's your favorite romantic gesture someone could do for you?",
        "What's the most seductive movie scene that turns you on?",
        "Do you enjoy spontaneous kisses in public?",
        "What's your favorite position for intimate moments?",
        "What's your favorite thing to wear that makes you feel sexy?",
        "What's the most intimate dream you've ever had?",
        "Do you like it when someone takes charge in the bedroom?",
        "What's your favorite body part to touch sensually?",
        "What's the most intimate text someone could send you?",
        "What's the most seductive way to send a message to someone?",
        "How do you like to set the mood for romance?",
        "What's your idea of the perfect flirt?",
        "How do you feel about playful teasing?",
        "What's something small but romantic that you love?",
        "What do you think makes someone unforgettable?",
        "What's the best compliment someone could give you in private?",
        "How do you feel about being pampered in a luxurious way?",
        "What's your idea of a perfect couple's massage?",
        "What's the most sensual thing you could do with someone?",
        "How do you feel about slow and deep kisses?",
        "What's your favorite way to be held during intimate moments?",
        "What's your idea of a sexy surprise?",
        "What's the most playful thing someone has done to tease you?",
        "What's the best way to flirt with you?",
        "What's the most romantic word someone could whisper to you?",
        "What's your idea of the best spontaneous date?",
        "Do you like when someone surprises you with a kiss?",
        "What's the most sensual smell that gets you in the mood?",
        "What's the most romantic thing you've ever done for someone?",
        "What's the best thing about being close to someone you like?",
        "What makes you feel most desired?",
        "What's your idea of a perfect kiss under the stars?",
        "What's the most sensual place you've ever kissed someone?",
        "How do you feel about passion-filled moments with someone?",
        "What's the most seductive way to send a text?",
        "What makes you feel completely turned on?",
        "What's the most romantic thing someone could do for you during a dinner?",
        "What's the sexiest compliment you've ever received?",
        "How do you like to express your desire?",
        "What's the best thing you can do to surprise your lover?",
        "What makes a kiss unforgettable?",
        "What's the most sensual activity you've ever done?",
        "What's your favorite way to cuddle with someone?",
        "What's the most intimate thing you've ever said to someone?",
        "What's the most romantic gesture you've ever witnessed?",
        "What do you find most irresistible about someone?",
        "What's the sexiest way to wake up next to someone?",
        "What makes you feel absolutely irresistible?",
        "What's the most seductive thing someone could do to catch your attention?",
        "What's the most passionate kiss you've ever had?",
        "What's your favorite way to initiate intimacy?",
        "What's the most flirtatious thing someone has done to you?",
        "What's your idea of the ultimate seductive evening?",
        "How do you feel about someone whispering sweet things to you?",
        "What's your idea of a perfect kiss?",
        "What's the most sensual thing you could say to someone?",
        "What's your favorite way to tease someone before kissing?",
        "What's the best way to be touched to feel desired?",
        "What's your favorite intimate activity to do together?",
        "How do you feel about slow, passionate eye contact?",
        "What's your idea of the most seductive music?",
        "What's your favorite intimate touch to get things started?",
        "What's the most romantic place you could imagine being kissed?",
        "How do you feel about being kissed unexpectedly?",
        "What's your favorite type of romantic gesture?",
        "What's the sexiest thing about being in a close relationship?",
        "How do you feel about stolen kisses in public?",
        "What's your idea of a romantic evening?",
        "What's the most intimate thing you've ever done with someone?",
        "How do you feel about passionate, spontaneous moments?",
        "What's the most exciting thing about being touched?",
        "What's your favorite romantic or sexy movie scene?",
        "What's the best surprise kiss you've ever had?",
        "What's your favorite memory of an intimate moment?",
        "How do you feel about whispers in your ear?",
        "What's the sexiest gesture someone can make?",
        "What's the best way to spend a night with someone you desire?",
        "What's your favorite way to flirt with someone you're into?",
        "How do you feel about being told you're irresistible?",
        "What's the best way to get someone's attention in a romantic way?",
        "What's the most intimate activity you can imagine doing?",
        "What's your idea of a sexy morning?",
        "What's the most romantic thing you've ever done in secret?",
        "What makes you feel desired?",
        "How do you like to be swept off your feet?",
        "What's the most exciting thing you've ever done in the name of love?",
        "How do you feel about the thrill of anticipation in a relationship?",
        "What's your idea of a passionate rendezvous?",
        "What's the most intimate thing someone has said to you?",
        "How do you feel about playful banter?",
        "What's your favorite part of a relationship?",
        "What's the best way to be held during a passionate moment?",
        "What makes a kiss unforgettable?",
        "What's the most intimate conversation you've had?",
        "What's your favorite intimate experience with someone?",
        "How do you feel about spontaneous moments of passion?",
        "What's the most seductive touch you've ever received?",
        "What's your idea of the perfect kiss?",
        "What's your favorite thing about someone being close to you?",
        "How do you feel about passionate eye contact?",
        "What makes someone irresistible to you?",
        "What's the sexiest thing you've ever done for a partner?",
        "What's your idea of a romantic getaway?",
        "What makes someone's smile incredibly attractive?",
        "How do you feel about someone taking control in the bedroom?",
        "What's the most sensual experience you've ever shared?",
        "What's the most seductive thing someone could do to make you smile?",
        "How do you feel about the anticipation of intimacy?",
        "What's the best way to show affection?",
        "What's the most intimate thing someone could do for you?",
        "How do you feel about quiet, tender moments of affection?",
        "What's your idea of a passionate kiss?",
        "What's the most sensual place you've ever been kissed?",
        "What's the most romantic place to kiss someone?",
        "What's the best way to surprise someone with intimacy?",
        "How do you feel about being told you're irresistible?",
        "What's the most intimate touch that makes you feel desired?",
        "What's the most seductive look you can give someone?",
        "How do you feel about passionate kisses in the rain?",
        "What's the most seductive way to make eye contact with someone?",
        "What's your idea of an unforgettable, intimate night?",
        "What's the most romantic gesture you've ever done for someone?",
        "How do you feel about being surprised with something intimate?",
        "What's your idea of the perfect sensual massage?",
        "What's the most seductive thing someone could whisper in your ear?",
        "What's the best way to build sexual tension with someone?",
        "What's the most intimate gesture someone could do for you?",
        "What's the best way to set the mood for romance?",
        "How do you feel about spontaneous romantic kisses in public?",
        "What's the sexiest thing someone could do to make you feel special?",
        "What's the best way to be held during a romantic moment?",
        "What's the most intimate moment you've shared with someone?",
        "How do you feel about slow, deep, passionate kisses?",
        "What's the most flirtatious thing someone could say to you?",
        "What makes someone irresistible to you?",
        "What's the best way to show someone you desire them?",
        "How do you feel about public displays of affection?",
        "What's the most intimate date idea you've ever had?",
        "What's your favorite way to tease someone in a playful way?",
        "What makes a touch feel incredibly seductive?",
        "What's your idea of a passionate, romantic evening?",
        "How do you feel about quiet, intimate moments in the bedroom?",
        "What's the most sensual way to kiss someone?",
        "What's the most intimate thing you've ever done for someone you love?"
    };

        private List<string> Crazy = new List<string>()
    {
        "What's the craziest thing you've ever done on a dare?",
        "If you could switch lives with anyone for 24 hours, who would it be?",
        "What's the wildest adventure you've ever had?",
        "What's the weirdest food you've ever tried and liked?",
        "What's the most outrageous thing you've done at a party?",
        "If you could do something illegal with no consequences, what would it be?",
        "What's the craziest thing you've done in public?",
        "What's the most out-of-character thing you've ever done?",
        "What's the most spontaneous decision you've ever made?",
        "What's the most unusual place you've ever slept?",
        "What's the wildest outfit you've ever worn?",
        "If you could pull off any insane stunt, what would you do?",
        "What's the craziest dream you've ever had?",
        "What's the most reckless thing you've done when you were younger?",
        "If you had to pick one wild animal to be your sidekick, what would it be?",
        "What's the craziest thing you've done to get someone's attention?",
        "What's the wildest experience you've had with a stranger?",
        "What's the weirdest thing you've done to pass time?",
        "If you could prank anyone, who would it be and what would you do?",
        "What's the weirdest thing you've done just to make someone laugh?",
        "What's the craziest thing you've done while under the influence?",
        "What's the wildest stunt you've seen someone else perform?",
        "What's the weirdest trend you've ever followed?",
        "What's the most unpredictable thing you've done on a dare?",
        "What's the craziest situation you've ever gotten yourself into on a night out?",
        "What's the weirdest prank you've ever pulled on a stranger?",
        "What's the most outrageous thing you've done in front of a crowd?",
        "What's the most dangerous thing you've done to impress someone?",
        "What's the wildest thing you've done during a vacation?",
        "What's the craziest thing you've done to get into a club or event?",
        "What's the most outrageous thing you've done to get revenge?",
        "What's the wildest thing you've done to make someone jealous?",
        "What's the most absurd thing you've done to prove a point?",
        "What's the weirdest thing you've done with a group of friends?",
        "What's the craziest thing you've done on a road trip?",
        "What's the most reckless thing you've done while traveling?",
        "What's the craziest outfit you've worn to a party?",
        "What's the most ridiculous dare you've completed and been proud of?",
        "What's the wildest thing you've done in a relationship?",
        "What's the most impulsive thing you've done on a weekend getaway?",
        "What's the craziest bet you've ever won or lost?",
        "What's the wildest decision you've ever made in the spur of the moment?",
        "What's the most unpredictable situation you've been in?",
        "What's the most spontaneous trip you've taken with no planning?",
        "What's the most ridiculous thing you've done in a supermarket?",
        "What's the wildest story you've heard from someone else?",
        "What's the craziest food challenge you've ever attempted?",
        "What's the weirdest excuse you've used to get out of a situation?",
        "What's the most absurd way you've ever spent money?",
        "What's the wildest dare you've made someone do?",
        "What's the weirdest dare someone has asked you to do?",
        "What's the most outrageous lie you've ever told?",
        "What's the craziest way you've ever entertained yourself alone?",
        "What's the most outlandish thing you've done to kill time?",
        "What's the weirdest dream you've ever had and acted on?",
        "What's the most reckless thing you've done at a party?",
        "What's the wildest thing you've ever done at a concert?",
        "What's the weirdest way you've been woken up?",
        "What's the craziest outfit you've worn just to shock people?",
        "What's the most insane thing you've done for a thrill?",
        "What's the most ridiculous situation you've found yourself in?",
        "What's the wildest thing you've done with a complete stranger?",
        "What's the weirdest adventure you've ever gone on?",
        "What's the craziest thing you've ever done to stand out?",
        "What's the most impulsive thing you've done for no reason?",
        "What's the wildest decision you've made in a relationship?",
        "What's the craziest way you've gotten revenge on someone?",
        "What's the most insane party you've ever thrown or attended?",
        "What's the wildest thing you've ever done for a dare?",
        "What's the most out-of-character thing you've ever done?",
        "What's the craziest lie you've told and actually got away with?",
        "What's the most unpredictable choice you've made on the spot?",
        "What's the wildest moment you've had at a family gathering?",
        "What's the craziest decision you've made while drunk?",
        "What's the most impulsive thing you've ever done on social media?",
        "What's the weirdest thing you've seen someone do at a wedding?",
        "What's the wildest thing you've done in the middle of the night?",
        "What's the most reckless thing you've ever done on vacation?",
        "What's the craziest thing you've done for a prank?",
        "What's the wildest way you've made an entrance to a party?",
        "What's the most bizarre situation you've gotten into with a stranger?",
        "What's the craziest thing you've done while in disguise?",
        "What's the wildest way you've gotten someone's attention?",
        "What's the most out-of-the-ordinary event you've thrown?",
        "What's the weirdest thing you've ever done at a holiday party?",
        "What's the most reckless thing you've done to impress someone?",
        "What's the craziest thing you've done in the name of friendship?",
        "What's the wildest thing you've done with a group of strangers?",
        "What's the weirdest dare you've done on a date?",
        "What's the most bizarre thing you've done while waiting for something?",
        "What's the wildest reaction you've had to a shocking situation?",
        "What's the craziest way you've gotten out of an awkward situation?",
        "What's the most impulsive thing you've done after a breakup?",
        "What's the wildest thing you've done to make a stranger laugh?",
        "What's the weirdest event you've been invited to?",
        "What's the most insane way you've spent an entire day?",
        "What's the craziest thing you've done just because you were bored?",
        "What's the weirdest thing you've done to get away with something?",
        "What's the most spontaneous way you've gotten yourself into trouble?",
        "What's the craziest thing you've done to break a routine?",
        "What's the most bizarre situation you've been in with family?",
        "What's the wildest thing you've done when you were in charge of something?",
        "What's the most ridiculous costume you've worn for Halloween?",
        "What's the wildest thing you've done to spice up your life?",
        "What's the most insane thing you've done when feeling adventurous?",
        "What's the craziest thing you've done on the spot without thinking?",
        "What's the wildest stunt you've seen on social media?",
        "What's the most bizarre job you've ever had or tried?",
        "What's the most unexpected thing you've done when under pressure?",
        "What's the craziest way you've ever met someone?",
        "What's the most outlandish thing you've done while partying?",
        "What's the weirdest challenge you've ever accepted from a friend?",
        "What's the wildest dare you've gotten during a road trip?",
        "What's the most insane prank you've pulled on your friends?",
        "What's the most spontaneous act of kindness you've done that was totally unex,pected?",
        "What's the wildest thing you've done in a hotel room?",
        "What's the weirdest talent or skill you've ever showcased?",
        "What's the most chaotic event you've ever organized?",
        "What's the most spontaneous and fun thing you've done on your birthday?",
        "What's the most ridiculous fear you have?",
        "If you could get away with any crime, what crime would you commit?",
        "What's the craziest bet you've ever made?",
        "What's the weirdest fashion trend you've ever followed?",
        "What's the most insane thing you'd do for a million dollars?",
        "What's the craziest party you've ever thrown?",
        "What's the most insane situation you've been in and survived?",
        "What's the weirdest hobby you've ever tried?",
        "If you could prank a celebrity, who would it be and what would you do?",
        "What's the craziest thing you've done while on vacation?",
        "What's the most outlandish story you've ever told someone?",
        "What's the most reckless thing you've done with friends?",
        "What's the most outrageous challenge you've ever accepted?",
        "If you could break any rule without consequences, which rule would you break?",
        "What's the weirdest place you've ever traveled to?",
        "What's the craziest stunt you'd want to pull off?",
        "What's the most impulsive decision you've ever made?",
        "What's the strangest thing you've done for a laugh?",
        "What's the weirdest situation you've ever gotten into?",
        "What's the craziest job you'd want to try for one day?",
        "What's the most out-of-the-box idea you've ever come up with?",
        "What's the weirdest lie you've ever told?",
        "If you could cause any chaos in the world, what would you do?",
        "What's the most embarrassing thing you've done and survived?",
        "What's the most insane thing you've done in a relationship?",
        "What's the wildest thing you've done for love?",
        "What's the weirdest food combination you secretly love?",
        "What's the craziest stunt you've ever pulled in front of your friends?",
        "What's the most dangerous thing you've ever done just for fun?",
        "What's the weirdest thing you've ever Googled?",
        "What's the most random dare you've ever accepted?",
        "What's the craziest place you've ever gone on a date?",
        "What's the most unpredictable thing you've ever done?",
        "What's the weirdest thing you've ever done with your friends?",
        "What's the most ridiculous thing you've believed as a child?",
        "What's the most out-of-the-box date idea you've had?",
        "What's the craziest road trip you've ever taken?",
        "What's the most chaotic situation you've ever found yourself in?",
        "What's the weirdest thing you've ever seen happen in public?",
        "What's the most unexpected thing that ever happened to you?",
        "What's the most dangerous thing you've ever done and got away with?",
        "If you could go on a crazy adventure right now, where would it be?",
        "What's the most insane dare you've pulled off successfully?",
        "What's the wildest thing you've done for attention?",
        "What's the most outlandish thing you've done in the name of fun?",
        "What's the weirdest prank you've played on someone?",
        "What's the most surprising thing you've done on a whim?",
        "What's the wildest dream you've ever had that felt too real?",
        "What's the weirdest thing you've seen someone do in public?",
        "What's the most eccentric thing you've done on a night out?",
        "What's the craziest gamble you've ever taken?",
        "What's the most unusual costume you've worn for a party?",
        "What's the weirdest thing you've done to impress someone?",
        "What's the most outrageous confession you've made?",
        "What's the craziest lie you've told and gotten away with?",
        "What's the wildest prank you've pulled off at work?",
        "What's the most bizarre thing you've ever done on a dare?",
        "What's the most unconventional way you've celebrated a holiday?",
        "What's the craziest thing you've done to get a free meal?",
        "What's the most absurd thing you've ever done for a thrill?",
        "What's the craziest stunt you've seen someone else pull off?",
        "What's the most spontaneous thing you've ever done on a weekend?",
        "What's the wildest dare you've ever witnessed?",
        "What's the craziest surprise you've ever given someone?",
        "What's the weirdest way you've ever spent money?",
        "What's the most insane reaction you've had to something unexpected?",
        "What's the most absurd thing you've done after a few drinks?",
        "What's the wildest risk you've ever taken in the name of fun?",
        "What's the most out-of-the-ordinary prank you've seen played?",
        "What's the craziest dare you've ever given to someone?",
        "What's the most insane moment of your life that you'll never forget?",
        "What's the wildest party you've ever attended?",
        "What's the most impulsive thing you've done that turned out to be amazing?",
        "What's the weirdest place you've ever had a date?",
        "What's the most unpredictable thing you've ever done on vacation?",
        "What's the most insane bet you've made and won?",
        "What's the craziest thing you've ever done for love or attention?",
        "What's the most ridiculous thing you've ever done in a relationship?",
        "What's the wildest decision you've ever made on a dare?",
        "What's the craziest outfit you've ever worn for a costume party?"  
    };

        private List<string> Flirty = new List<string>()
    {
        "What's the most attractive thing about a person—looks or personality?",
        "If you could take anyone here to anywhere in the world right now, who would it be?",
        "If you played truth or dare, what's the first question you'd ask?",
        "If you had to write a flirty pickup line right now, what would it be?",
        "Would you rather have a candlelit dinner or a fun night at an amusement park?",
        "If you were being dared to send a risky text to your crush right now, would you do it?",
        "What's your idea of the perfect first date?",
        "If you were given three wishes and you had to use one on anyone here, what would you wish for?",
        "What's your favorite way to get someone's attention?",
        "Have you ever had a secret crush on someone in this room?",
        "What's the most romantic thing you've ever done for someone?",
        "If you could kiss anyone here, who would it be?",
        "What would you do if someone sent you a cute message right now?",
        "Do you believe in love at first sight?",
        "What's the best way to flirt, in your opinion?",
        "If I were to steal your attention, how would I do it?",
        "How do you feel about a spontaneous adventure?",
        "What's your favorite type of date night?",
        "Do you think there's a perfect match for everyone?",
        "How would you react if someone wrote you a heartfelt letter?",
        "Would you want to be swept off your feet?",
        "What's your go-to move when you want to impress someone?",
        "How do you feel about people sending surprise gifts?",
        "What would you do if someone just showed up with flowers for you?",
        "Do you like being surprised, or do you prefer knowing what's coming?",
        "How do you usually like someone to show interest in you?",
        "Do you enjoy playful teasing?",
        "How do you feel about someone holding your hand unexpectedly?",
        "Would you rather receive a compliment or give one?",
        "How do you like to be flirted with?",
        "What's the most daring thing you'd do for love?",
        "How do you feel about spontaneous kisses?",
        "What's the best way to flirt with you?",
        "Do you think you're a good flirt?",
        "What's the cutest thing someone has done for you?",
        "Do you believe in love letters?",
        "How would you feel about being serenaded?",
        "What's your idea of a perfect evening?",
        "Would you rather have a long conversation or share a quiet moment with someone?",
        "Do you find it attractive when someone makes you laugh?",
        "Would you send a cute message to someone you like?",
        "How do you feel about romantic surprises?",
        "What's one thing that's always guaranteed to make you smile?",
        "If you had to give someone a compliment right now, what would it be?",
        "What's your favorite romantic gesture?",
        "Do you like it when someone takes the lead?",
        "What's the most romantic date you've ever been on?",
        "How do you feel about slow dancing?",
        "What would you do if someone gave you a playful wink?",
        "Do you think compliments are a good way to flirt?",
        "How would you feel if someone took you on a surprise date?",
        "What's the most fun way to flirt with you?",
        "Do you believe flirting is an art?",
        "How do you feel about a little friendly competition when flirting?",
        "What's your idea of a perfect cuddle session?",
        "Would you rather receive a handwritten note or a cute text?",
        "What's the best way to impress you?",
        "How would you feel if someone made you blush?",
        "If someone said something sweet to you, how would you react?",
        "What's the most charming thing someone could say to you?",
        "Do you think it's fun to flirt with someone you don't know?",
        "How would you feel if someone took you out for a surprise romantic dinner?",
        "Do you like it when someone gives you a compliment out of nowhere?",
        "How do you feel about playful nicknames?",
        "What's the most attractive quality someone can have?",
        "How would you feel if someone told you you're their type?",
        "What's your idea of a perfect relationship?",
        "Would you rather receive a kiss or a hug?",
        "How do you feel about spontaneous adventures?",
        "What would you do if someone flirted with you over text?",
        "How would you feel if someone made you the center of their attention?",
        "Do you think it's cute when someone blushes?",
        "How do you feel about a surprise kiss on the cheek?",
        "What's the best way to show someone you care?",
        "How would you feel about someone surprising you with something meaningful?",
        "Do you like to be the one who makes the first move?",
        "What's the most romantic thing you've ever done for someone?",
        "How do you feel about someone surprising you with a sweet gesture?",
        "Would you want someone to sing you a song?",
        "How do you feel about someone showing up with a simple, sweet gift?",
        "What's your favorite kind of playful banter?",
        "Would you rather have a spontaneous adventure or a relaxed evening?",
        "How do you feel about someone giving you a meaningful compliment?",
        "What's the most fun thing someone can do to flirt with you?",
        "Do you like it when someone is bold with their flirts?",
        "What would you do if someone sent you a flirty message?",
        "Do you like the idea of sending flirty texts?",
        "How would you react if someone teased you in a playful way?",
        "What's the best way for someone to get your attention?",
        "Would you be surprised if someone made a grand gesture for you?",
        "How would you feel if someone tried to make you laugh with a silly joke?",
        "Would you rather get a compliment on your looks or your personality?",
        "How would you feel if someone complimented your smile?",
        "Do you like being the one to make the first move?",
        "Would you like it if someone gave you a surprise hug?",
        "How do you feel about receiving little surprises from someone you like?",
        "What's the most thoughtful thing someone could do for you?",
        "Would you rather share a quiet moment or have a fun night out?",
        "Do you think flirting is a form of art?",
        "Would you prefer a playful conversation or a serious one?",
        "How do you feel about someone calling you cute?",
        "Would you like it if someone made you feel special unexpectedly?",
        "How do you feel about playful teasing?",
        "Would you rather have someone surprise you with flowers or a handwritten note?",
        "How do you feel about someone going out of their way to make you smile?",
        "Would you like it if someone serenaded you?",
        "Do you think a little flirting can be fun?",
        "How would you feel if someone gave you a meaningful compliment?",
        "Would you prefer a date night in or a night out on the town?",
        "How do you feel about a person making you feel special with their words?",
        "Do you think someone can be cute and playful at the same time?",
        "Would you like it if someone tried to impress you with their charm?",
        "What's your idea of the perfect surprise?",
        "Would you want someone to tell you a funny story to make you smile?",
        "How would you feel if someone wanted to make your day better?",
        "Do you find it cute when someone flirts with you over text?",
        "Would you want someone to take you on a surprise date?",
        "How do you feel about playful surprises?",
        "Do you enjoy someone making you laugh with a funny joke?",
        "What would be the best way for someone to flirt with you?",
        "How do you feel about someone calling you their favorite person?",
        "Do you find it sweet when someone remembers little details about you?",
        "How would you feel if someone gave you a compliment that made you blush?",
        "Do you believe in love at first sight?",
        "Would you be impressed if someone tried hard to impress you?",
        "Do you enjoy a bit of playful teasing?",
        "How do you feel about someone being bold with their compliments?",
        "Would you like it if someone showed you that you were important to them?",
        "How do you feel about sweet surprises?",
        "Would you want to go on an unexpected adventure with someone?",
        "How would you feel if someone kept a secret just to surprise you later?",
        "Do you find it romantic when someone goes out of their way for you?",
        "How do you feel about someone remembering your favorite things?",
        "Would you like it if someone gave you a spontaneous compliment?",
        "What's the best way for someone to get to know you?",
        "How do you feel about someone remembering your favorite things about you?",
        "Would you want someone to surprise you with something special?",
        "Do you like it when someone calls you their favorite?",
        "How would you feel if someone went out of their way to make you happy?",
        "Do you think it's cute when someone shows affection unexpectedly?",
        "How would you feel about someone leaving you a flirty message?",
        "What would you think if someone asked you to go somewhere fun right now?",
        "Would you like to be swept off your feet by someone charming?",
        "How do you feel about someone calling you beautiful out of the blue?",
        "Would you like it if someone wrote you a sweet note?",
        "How do you feel about someone calling you their sweetheart?",
        "What would you think if someone wanted to steal you away for a fun date?",
        "How do you feel about someone giving you compliments unexpectedly?",
        "Would you prefer a quiet moment or a fun adventure with someone?",
        "How would you feel about someone being spontaneous with you?",
        "Would you like someone to serenade you?",
        "Do you think flirting can be a lot of fun?",
        "How would you feel if someone said you were their perfect match?",
        "Would you want someone to surprise you with a romantic gesture?",
        "Do you think it's fun to tease someone you like?",
        "Would you like it if someone sent you a sweet text out of nowhere?",
        "How do you feel about a little surprise flirtation?",
        "Would you want someone to surprise you with a spontaneous kiss?",
        "How would you feel if someone showed you they cared with little gestures?",
        "Would you like it if someone complimented you in a playful way?",
        "How would you feel if someone gave you a sincere compliment?",
        "Do you think a surprise text could make your day?",
        "Would you want to go on an unexpected date with someone?",
        "How do you feel about sweet and sincere compliments?",
        "Would you like it if someone asked you out on a surprise date?",
        "How would you feel if someone offered to take you on a fun adventure?",
        "Would you like someone to serenade you with a love song?",
        "How do you feel about playful flirting?",
        "Would you want someone to take you out and surprise you?",
        "How would you feel if someone randomly sent you a sweet text?",
        "What do you think of someone calling you their dream person?",
        "Would you like it if someone was charmingly flirtatious with you?",
        "How do you feel about a flirty conversation?",
        "Would you want someone to surprise you with a cute message?",
        "How do you feel about flirty texts?",
        "Would you like it if someone sent you a surprise compliment?",
        "How would you feel if someone made your day by being sweet?",
        "What would you think if someone left you a sweet note unexpectedly?",
        "Would you like it if someone made you blush with a playful comment?",
        "How do you feel about romantic surprises?",
        "Would you want someone to make you feel special in unexpected ways?",
        "Would you like it if someone planned a spontaneous romantic evening?",
        "How do you feel about someone whispering sweet things to you?",
        "Would you like someone to surprise you with a romantic gesture?",
        "How do you feel about a little teasing in a conversation?",
        "Would you like someone to take you on a spontaneous romantic getaway?",
        "How would you feel if someone showed you they cared with a little surprise?",
        "Do you like it when someone surprises you with affection?",
        "Would you want to be surprised with a fun night out?",
        "How do you feel about unexpected affection?",
        "Would you like it if someone showed you affection unexpectedly?",
        "How would you feel if someone invited you out on a surprise date?",
        "Would you want someone to surprise you with something romantic?",
        "How do you feel about someone teasing you in a playful way?",
        "Would you like someone to surprise you with a spontaneous date?",
        "Would you be surprised if someone showed up with something cute for you?",
        "How would you feel about someone telling you how amazing you are?",
        "Would you like it if someone took you on an unplanned adventure?",
        "Would you be happy if someone left you a sweet surprise note?",
        "How do you feel about receiving spontaneous flirtation?"  
    };

        private List<string> Edgy = new List<string>()
    {
        "What would you do if you had no rules for a day?",
        "Would you rather break the law for fun or follow it to the letter?",
        "Have you ever gotten into trouble and enjoyed it?",
        "What's the craziest thing you've ever done to get attention?",
        "If you could live outside society's rules, what would your life look like?",
        "Do you ever question everything you've been taught?",
        "Would you rather be feared or loved?",
        "What's your biggest regret that you secretly loved doing?",
        "Would you sell your soul for the ultimate power?",
        "Have you ever made a decision that you knew was reckless?",
        "What's the most rebellious thing you've done this week?",
        "What's your darkest secret that you've never told anyone?",
        "Would you ever betray someone close to you for personal gain?",
        "If you could destroy one part of society, which would it be?",
        "Do you believe rules are meant to be broken?",
        "What's the most dangerous thing you've ever wanted to do?",
        "Would you be willing to hurt someone to get what you want?",
        "What do you think happens after death—endless void or a new beginning?",
        "Do you think people are born evil or shaped by their environment?",
        "What's the line between loyalty and manipulation?",
        "Would you choose to live a perfect life if it meant no freedom?",
        "What's the biggest lie you've told to get away with something?",
        "If you had to live as an outcast, how would you survive?",
        "What do you think is the most powerful emotion?",
        "Do you ever wish the world would just burn and start over?",
        "What's the worst decision you've made but don't regret?",
        "Have you ever purposely broken someone's heart?",
        "What would you do if no one ever judged you again?",
        "Would you ever choose chaos over peace?",
        "What's something you would never do… unless you were pushed?",
        "Do you think you could handle being the villain in your own story?",
        "If your life were a movie, would you be the hero or the anti-hero?",
        "What's your idea of the perfect rebellion?",
        "What would happen if society crumbled—would you thrive or panic?",
        "Would you risk everything for the taste of true freedom?",
        "What's the most twisted thing you've ever done?",
        "What's one thing that could push you to break every rule?",
        "Do you think anyone is truly pure, or are we all tainted?",
        "How far would you go to achieve your darkest desires?",
        "What's one thing you'd change in the world, even if it hurt?",
        "Is it worth sacrificing a little of yourself to survive?",
        "What's your breaking point before you snap?",
        "Do you trust people who follow the rules, or those who bend them?",
        "What's the most dangerous idea you've ever entertained?",
        "What would it take for you to become a villain?",
        "What do you think happens when someone truly loses control?",
        "Have you ever walked away from something just because it was too easy?",
        "What would you do if you could erase all your past mistakes?",
        "Is chaos really so bad, or is it just misunderstood?",
        "What's one thing about you that no one would believe?",
        "If you could erase one thing from existence, what would it be?",
        "How do you handle a situation when all options seem wrong?",
        "Would you ever sacrifice an innocent to save yourself?",
        "How do you define true freedom?",
        "What's something that would make you snap and completely lose it?",
        "Do you think breaking the rules makes someone strong or weak?",
        "What's one dangerous game you'd play if there were no consequences?",
        "Have you ever gone too far to prove a point?",
        "What's the most rebellious thing you'd do for a laugh?",
        "Would you do something illegal if you could get away with it?",
        "What's your most controversial opinion?",
        "Do you believe in fate, or do we all choose our path?",
        "If you had to erase your moral compass, would you?",
        "What would you do if your worst enemy offered you a deal?",
        "What's your limit when it comes to bending the rules?",
        "How would you survive a lawless world?",
        "Would you give up your humanity for the ultimate power?",
        "What's the most intense risk you've ever taken?",
        "Do you think you're capable of true evil?",
        "What do you do when you realize you've crossed a line?",
        "Have you ever felt like the world owes you something?",
        "Would you start a revolution if it meant changing the world?",
        "What's the price of betrayal?",
        "What's something you know you shouldn't do but still want to?",
        "If you could erase all traces of your past, would you?",
        "Do you think true happiness comes from chaos or control?",
        "What's the most dangerous thing you've done for love?",
        "If you were a villain, what would be your signature move?",
        "What would you do if you knew there were no consequences?",
        "What's the most reckless thing you've done in the name of freedom?",
        "Have you ever pushed someone past their breaking point?",
        "If you could cause one major change in the world, what would it be?",
        "Do you think society needs rules to survive, or could it thrive without them?",
        "What's one taboo you've always wanted to break?",
        "If you could betray anyone without remorse, who would it be?",
        "What's something you'd do if you knew it would make you famous?",
        "Have you ever destroyed something important just to see what would happen?",
        "What's the worst thing you've done for revenge?",
        "Would you break the law if you knew you'd never get caught?",
        "How far would you go to protect yourself?",
        "If you could erase all rules from your life, what would you do?",
        "What would you do if you had the chance to rule the world?",
        "Have you ever crossed a moral line for something you wanted?",
        "What's the biggest lie you've told to make yourself feel better?",
        "Do you think it's better to fight back or let the world break you?",
        "What's something you'd do just to feel alive?",
        "Would you sacrifice everything for a chance to change your life?",
        "Have you ever felt like you're playing a dangerous game with fate?",
        "What's the one rule you would break in a heartbeat?",
        "If you had to break someone's heart to get ahead, would you do it?",
        "What's the most rebellious thing you've ever done at work?",
        "Do you think power corrupts, or does it expose the true self?",
        "What's the most chaotic decision you've ever made?",
        "How do you handle situations when there's no right answer?",
        "Would you kill for the perfect life?",
        "What's your darkest ambition?",
        "Have you ever done something just to prove you could?",
        "If you were a villain, what would your backstory be?",
        "What's the wildest conspiracy theory you believe in?",
        "Would you ever steal something you couldn't afford?",
        "If you could never be held accountable for anything, what would you do?",
        "What's something that keeps you up at night?",
        "If your life were a crime story, what would your role be?",
        "What's the most dangerous habit you've ever picked up?",
        "Do you think society would fall apart without rules?",
        "What's the most rebellious thing you've ever done for someone else?",
        "What would you do if you could get away with murder?",
        "Have you ever lied to make someone think you were better than you are?",
        "If you had the chance to live forever, would you take it?",
        "What's the greatest risk you've taken for love?",
        "What would it take for you to abandon your principles?",
        "What's the one thing that makes you feel invincible?",
        "What's something you would do in an alternate reality?",
        "Would you cheat if you knew no one would find out?",
        "What's your idea of the perfect crime?",
        "How far would you go for revenge?",
        "What's something you'd do if there were no consequences?",
        "What's the most dangerous risk you've ever taken?",
        "Would you be willing to do something morally wrong if it benefited you?",
        "What's something you've done and would never do again?",
        "If you could restart your life, what would you change?",
        "What's something you would sacrifice for ultimate power?",
        "What would you do if you knew no one would judge you?",
        "Would you kill someone to save someone else?",
        "What's the worst thing you've done for the sake of power?",
        "If your life was a heist, who would you be?",
        "Would you betray a friend for personal gain?",
        "What's something you'd sacrifice to escape your current life?",
        "What's the most controversial thing you've ever said?",
        "Would you ever start an underground movement?",
        "What would you do if you knew you couldn't fail?",
        "How far would you go to survive in a dystopian world?",
        "What's the most dangerous thing you've ever tried?",
        "Would you go to the extreme for fame and fortune?",
        "What's the darkest side of your personality?",
        "Would you betray everything you know for a fresh start?",
        "What's the one thing you'd do to change your destiny?",
        "How far would you go to uncover the truth?",
        "What's the most rebellious thing you've ever said?",
        "What's the greatest risk you've taken without thinking twice?",
        "Would you kill for something you believe in?",
        "What's something that could change your life forever?",
        "Would you sacrifice a part of yourself to get what you want?",
        "What's the most reckless thing you've done for fun?",
        "Would you abandon your morals if it meant you could get ahead?",
        "What would you do if no one knew your past?",
        "If you could live without consequences, how would your life change?",
        "What's something you've done that you're proud of, but no one knows?",
        "Would you betray your family to save yourself?",
        "What's your secret weapon when life gets tough?",
        "What's the craziest thing you'd do to escape your problems?",
        "If you could rewrite your life story, what would you change?",
        "What's the most rebellious thing you've done in your career?",
        "Would you risk everything for one last shot at success?",
        "How far would you go to make your dreams a reality?",
        "What's the one rule you always break?",
        "Would you ever go to war to protect what you believe in?",
        "What's the biggest thing you've done for personal gain?",
        "What's the one thing that always makes you feel powerful?",
        "Would you sacrifice your freedom for something greater?",
        "What's the worst decision you've ever made but don't regret?",
        "What would you do if you had no responsibilities?",
        "Would you betray everyone you know for ultimate power?",
        "What's something you'd never tell anyone, even if they asked?",
        "What would you do if you could never go back?",
        "Would you break a promise if it meant you could gain something?",
        "What's the most rebellious thing you've done for yourself?",
        "Would you ever risk everything for love?",
        "What's something you secretly wish you could change about yourself?",
        "What's the biggest challenge you've faced that made you stronger?",
        "Would you ever leave everything behind to start over?",
        "What's the most dangerous thing you'd do for a chance at success?",
        "If you could be anyone else, who would it be?",
        "What's the most extreme thing you've done for the thrill of it?",
        "Would you break the rules to protect someone you love?",
        "What's the most radical change you've made in your life?",
        "What's your ultimate goal, even if it means losing everything?",
        "Would you sacrifice your future for a shot at fame?",
        "What's something you'd do if you didn't care about the consequences?",
        "How far would you go to find true happiness?",
        "Would you betray someone to protect your future?",
        "What would you do if you knew you couldn't fail?",
        "Would you ever sabotage someone to get what you want?",
        "What's the most risky thing you've ever tried?",
        "What's your definition of ultimate power?",
        "Would you sacrifice your soul for unimaginable power?",
        "What's the one thing you fear you'll never be able to have?",
        "What's the most dangerous thought you've had?",
        "Would you go to any lengths to make someone believe in you?",
        "What's the one thing you would sacrifice to make your dreams come true?"
    };

        private List<string> Rush = new List<string>()
    {
            "Elephant", "Dog", "Cat", "Horse", "Lion", "Tiger", "Shark", "Eagle", "Dolphin", "Monkey",
            "Cow", "Goat", "Sheep", "Zebra", "Kangaroo", "Giraffe", "Bear", "Crocodile", "Snake", "Turtle",
            "Chair", "Table", "Book", "Pen", "Spoon", "Fork", "Plate", "Mug", "Bottle", "Clock",
            "Television", "Radio", "Laptop", "Keyboard", "Mouse", "Pillow", "Blanket", "Towel", "Mirror",
            "Car", "Bicycle", "Bus", "Kitchen", "Airplane", "Helicopter", "Yacht", "Submarine",
            "House", "Bridge", "Skyscraper", "Lighthouse", "Castle", "Tent", "Barn", "Hut", "Igloo",
            "Rock", "Mountain", "Tree", "River", "Ocean", "Waterfall", "Desert", "Cloud", "Volcano", "Iceberg",
            "Shirt", "Pants", "Hat", "Jacket", "Shoes", "Socks", "Gloves", "Sunglasses", "Belt", "Scarf",
            "Apple", "Banana", "Orange", "Bread", "Cheese", "Meat", "Fish", "Rice", "Cake", "Chocolate",
            "Football", "Basketball", "Tennis Racket", "Baseball Bat", "Boxing Gloves", "Skates", "Surfboard", "Helmet", "Dumbbell",
            "Dog", "Cat", "Cow", "Horse", "Goat", "Sheep", "Duck", "Frog", "Eagle", "Bear",  
            "Deer", "Rabbit", "Turtle", "Fish", "Shark", "Whale", "Dolphin", "Parrot", "Snake", "Lizard",  
            "Chicken", "Owl", "Fox", "Wolf", "Tiger", "Lion", "Zebra", "Giraffe", "Elephant", "Hippo",
            "Chair", "Table", "Bed", "Lamp", "Door", "Window", "Fan", "Mirror", "Couch", "Clock",  
            "Phone", "Laptop", "Keyboard", "Mouse", "Pencil", "Pen", "Book", "Notebook", "Backpack", "Shoes",  
            "Hat", "Glasses", "Bottle", "Cup", "Plate", "Spoon", "Fork", "Bowl", "Scissors", "Rope",
            "Rock", "Tree", "Flower", "Grass", "Leaf", "Cloud", "Sun", "Moon", "Star", "Rain",  
            "Snow", "Wind", "River", "Ocean", "Lake", "Mountain", "Hill", "Valley", "Island", "Desert",  
            "Cave", "Waterfall", "Beach", "Sand", "Ice", "Fire", "Stone", "Bush", "Moss", "Pond",
            "Apple", "Banana", "Orange", "Grapes", "Peach", "Pear", "Cherry", "Strawberry", "Watermelon", "Tomato",  
            "Potato", "Carrot", "Onion", "Garlic", "Corn", "Rice", "Bread", "Butter", "Cheese", "Egg",  
            "Milk", "Honey", "Pizza", "Burger", "Cake", "Dining", "Candy", "Chocolate", "Fish", "Chicken",
            "House", "Barn", "Bridge", "School", "Church", "Store", "Tower", "Castle", "Factory", "Hotel",  
            "Hospital", "Library", "Market", "Farm", "Garage", "Tent", "Cabin", "Stadium", "Palace", "Airport",
            "Car", "Bus", "Truck", "Bike", "Train", "Boat", "Ship", "Plane", "Taxi", "Ambulance",  
            "Firetruck", "Helicopter", "Motorcycle", "Scooter", "Tractor", "Submarine", "Jet", "Yacht", "Balloon", "Cart",
            "Shirt", "Pants", "Shorts", "Skirt", "Dress", "Jacket", "Socks", "Gloves", "Scarf", "Belt",  
            "Tie", "Earring", "Necklace", "Watch", "Bracelet", "Helmet", "Spider", "Maize", "Slippers", "Boots",
            "Hammer", "Saw", "Nail", "Drill", "Wrench", "Plier", "Screw", "Tape", "Ruler", "Brush",  
            "Eraser", "Marker", "Compass", "Scalpel", "Tongs", "Ladder", "Flashlight", "Lock", "Key", "Bucket",
            "Ball", "Balloon", "Toy", "Doll", "Whale", "Kite", "Clock", "Radio", "TV", "Candle",  
            "Soap", "Towel", "Blanket", "Sniper", "Basket", "Suitcase", "Map", "Flag", "Rope", "Mirror",
            "Ant", "Bee", "Butterfly", "Crab", "Crocodile", "Dove", "Electric fish", "Goose", "Hedgehog", "Jellyfish",  
            "Kangaroo", "Leopard", "Mole", "Newt", "Octopus", "Panda", "Penguin", "Quail", "Raccoon", "Seagull",  
            "Slug", "Squirrel", "Toad", "Vulture", "Jollof Rice", "Yak", "Chameleon", "Pigeon", "Donkey", "Gorilla",
            "Envelope", "Air", "Breeze", "Calculator", "Razor", "Toothbrush", "Shampoo", "Lotion", "Comb", "Lipstick",  
            "Cork", "Battery", "Sponge", "Sewing Needle", "Dice", "Whistle", "Thermometer", "Medal", "Goggles", "Locket",  
            "Keychain", "Handbag", "Duster", "Chalk", "Sunscreen", "Flyswatter", "Bulb", "Headphones", "Joystick", "USB Drive",
            "Volcano", "Glacier", "Coral", "Pebble", "Cactus", "Superman", "Vine", "Breeze", "Fog", "Wonderwoman",  
            "Lava", "Seashell", "Spiderman", "Butter", "Driftwood", "Tide", "Dew", "Icicle", "Cliff", "Meadow",
            "Mango", "Pawpaw", "Plum", "Coconut", "Avocado", "Blueberry", "Cucumber", "Lettuce", "Spinach", "Peanut",  
            "Fan", "Charger", "Facebook Logo", "Yogurt", "Hoodie", "Donut", "Pasta", "Pancake", "Cereal", "Steak",  
            "Cinema", "Popcorn", "Pickle", "Jam", "Sushi", "Noodles", "Sword", "Lasagna", "Meatball", "Hotdog",
            "Mosque", "Synagogue", "Fort", "Greenhouse", "Warehouse", "Lighthouse", "Crocs", "Prison", "Opera House", "Mall",  
            "Bus Stop", "Train Station", "Cinema", "Aquarium", "Museum", "Gas Station", "Campsite", "Parking Lot", "Windmill", "Playground",
            "Rickshaw", "Barge", "Canoe", "Raft", "Hovercraft", "Cruise Ship", "Glider", "Cable Car", "Bulldozer", "Forklift",  
            "Ambulance", "Trolley", "Dirt Bike", "Skateboard", "Roller Skates", "Ant hill", "Snowmobile", "Rowboat", "Toilet", "Tank",
            "Raincoat", "Swimsuit", "Overalls", "Cape", "Water", "Beret", "Turban", "Hoodie", "Wristband", "Ankle Boots",  
            "Choose a word", "Hairband", "Lionel Messi", "Christiano Ronaldo", "Turtleneck", "Water ripples", "Sandal", "Stockings", "Ice cubes", "Bathrobe",
            "Chandelier", "Barometer", "Telescope", "Stethoscope", "Microscope", "Magnifying Glass", "Crowbar", "Screwdriver", "Chainsaw", "Mallet",  
            "Chisel", "Tongs", "Pickaxe", "Gun", "Axe", "Clamp", "Wrench", "Drill Bit", "Paintbrush", "Measuring Tape",
            "Ambulance", "Umbrella", "Keypad", "Compass", "Lantern", "Fireplace", "Silence", "Den", "Luggage", "Funnel",  
            "Egg yolk", "Toaster", "Microwave", "Blender", "Vacuum Cleaner", "Sewing Machine", "Aquarium", "Boomerang", "Dumbbell", "TV Remote"
    };

    public string GetMostLikelyQuestion(int index)
    {
        if (index >= 0 && index < MostLikely.Count)
        {
            return MostLikely[index];
        }
        return "No question available.";
    }

    public string GetNameThreeThingsQuestion(int index)
    {
        if (index >= 0 && index < NameThreeThings.Count) // Correct list used
        {
            return NameThreeThings[index]; // Correct list used
        }
        return "No question available.";
    }

        public string GetRushQuestion(int index)
    {
        if (index >= 0 && index < Rush.Count) // Correct list used
        {
            return Rush[index]; // Correct list used
        }
        return "No question available.";
    }

        public string GetSexyQuestion(int index)
    {
        if (index >= 0 && index < Sexy.Count)
        {
            return Sexy[index];
        }
        return "No question available.";
    }

        public string GetCrazyQuestion(int index)
    {
        if (index >= 0 && index < Crazy.Count)
        {
            return Crazy[index];
        }
        return "No question available.";
    }

        public string GetFlirtyQuestion(int index)
    {
        if (index >= 0 && index < Flirty.Count)
        {
            return Flirty[index];
        }
        return "No question available.";
    }

        public string GetEdgyQuestion(int index)
    {
        if (index >= 0 && index < Edgy.Count)
        {
            return Edgy[index];
        }
        return "No question available.";
    }

    public int GetQuestionCount()
    {
        return MostLikely.Count;
    }

    public int GetNameThreeThingsQuestionCount()
    {
        return NameThreeThings.Count;
    }

        public int GetRushCount()
    {
        return Rush.Count;
    }

    

        public int GetSexyCount()
    {
        return Sexy.Count;
    }

        public int GetCrazyCount()
    {
        return Crazy.Count;
    }

        public int GetFlirtyCount()
    {
        return Flirty.Count;
    }

        public int GetEdgyCount()
    {
        return Edgy.Count;
    }

}
